# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\tflowmodus\"\xd6\x01\n\x0fTelemetrySample\x12\x13\n\x0bsupplier_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x18\n\x10sample_time_unix\x18\x03 \x01(\x03\x12\x0f\n\x07ttft_ms\x18\x04 \x01(\x02\x12\x19\n\x11total_duration_ms\x18\x05 \x01(\x02\x12\x14\n\x0ckv_cache_hit\x18\x06 \x01(\x08\x12\x15\n\rbilled_tokens\x18\x07 \x01(\x05\x12\x13\n\x0bstatus_code\x18\x08 \x01(\x05\x12\x14\n\x0chealth_state\x18\t \x01(\t\"\x9e\x01\n\x0e\x43laimDeviation\x12\x13\n\x0bsupplier_id\x18\x01 \x01(\t\x12\x13\n\x0bmetric_name\x18\x02 \x01(\t\x12\x15\n\rclaimed_value\x18\x03 \x01(\x02\x12\x14\n\x0c\x61\x63tual_value\x18\x04 \x01(\x02\x12\x19\n\x11\x64\x65viation_percent\x18\x05 \x01(\x02\x12\x1a\n\x12\x63\x61lculated_at_unix\x18\x06 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYSAMPLE']._serialized_start=29
  _globals['_TELEMETRYSAMPLE']._serialized_end=243
  _globals['_CLAIMDEVIATION']._serialized_start=246
  _globals['_CLAIMDEVIATION']._serialized_end=404
# @@protoc_insertion_point(module_scope)
