# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flowmodus.schemas import supplier_pb2 as supplier__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\x12\tflowmodus\x1a\x0esupplier.proto\"\x84\x01\n\x0fRegistryPackage\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x19\n\x11published_at_unix\x18\x02 \x01(\x03\x12\x31\n\tsuppliers\x18\x03 \x03(\x0b\x32\x1e.flowmodus.SupplierDeclaration\x12\x12\n\nsignatures\x18\x04 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRYPACKAGE']._serialized_start=46
  _globals['_REGISTRYPACKAGE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
